# Generated by Django 3.1.14 on 2024-06-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_streaming_app', '0001_initial'),
    ]

    operations = [
    ]
