# Generated by Django 3.1.14 on 2024-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_streaming_app', '0002_auto_20240616_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
