# Generated by Django 3.1.14 on 2024-06-16 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_streaming_app', '0003_auto_20240616_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
